; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = nucleo_g071rb 
framework = arduino

board_build.mcu = stm32g070kbt6
board_build.f_cpu = 64000000L

upload_protocol = stlink
debug_tool = stlink

build_flags = 
    -D ARDUINO_GENERIC_G070KBTX
    -D PIN_WIRE_SDA=PA12
    -D PIN_WIRE_SCL=PA11

# 2. Environment for I2C Scanner
[env:i2c_scanner]
# Fixed the warning by using build_src_filter
build_src_filter = +<*> -<main_charger_test.cpp> -<IP5306.cpp> -<IP5306.h>


# 3. Environment for Charger Test
[env:charger_test]
# Fixed the warning by using build_src_filter
build_src_filter = +<*> -<main_i2c_scanner.cpp>