; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = nucleo_g071rb 
framework = arduino

board_build.mcu = stm32g070kbt6
board_build.f_cpu = 64000000L

upload_protocol = stlink
debug_tool = stlink

build_flags = 
    -D ARDUINO_GENERIC_G070KBTX
    -D PIN_WIRE_SDA=PA12
    -D PIN_WIRE_SCL=PA11

# 2. Environment for I2C Scanner
[env:i2c_scanner]
build_src_filter = +<main_i2c_scanner.cpp> +<clock_config.cpp>


# 3. Environment for Charger Test
[env:charger_test]
build_src_filter = +<main_charger_test.cpp> +<clock_config.cpp>


# 4. Environment for Key Test
[env:key_test]
build_src_filter = +<main_key_test.cpp> +<clock_config.cpp>


# 5. Environment for Light Load Shutdown Test
[env:light_load_shutdown_test]
build_src_filter = +<main_light_load_shutdown_test.cpp> +<clock_config.cpp>


# 6. Environment for NeoPixel Button + Charger Test
[env:neopixel_button_test]
build_src_filter = +<main_neopixel_button_test.cpp> +<clock_config.cpp>
lib_deps =
    bxparks/AceButton
    adafruit/Adafruit NeoPixel


# 7. Environment for IP5306 I2C Watchdog Test
[env:ip5306_i2c_watchdog]
build_src_filter = +<main_ip5306_i2c_watchdog.cpp> +<clock_config.cpp>


# 8. Environment for Stop 1 Wakeup Test
[env:stop1_test]
build_src_filter = +<main_stop1_test.cpp> +<clock_config.cpp>
lib_deps =
    jgromes/RadioLib


# 9. Environment for Stop 1 MCU-Only Wakeup Test
[env:stop1_mcu_only]
build_src_filter = +<main_stop1_mcu_only.cpp> +<clock_config.cpp>


# 10. Environment for Stop 1 No-LoRa (Unpopulated Board) Test
[env:stop1_no_lora]
build_src_filter = +<main_stop1_no_lora.cpp> +<clock_config.cpp>


# 11. Environment for Shutdown Mode Wakeup Test
[env:shutdown_test]
build_src_filter = +<main_shutdown_test.cpp> +<clock_config.cpp>


# 12. Environment for Actuation Module Stop 1 Sleep/Wake
[env:stop1_actuation]
build_src_filter = +<main_stop1_actuation.cpp> +<clock_config.cpp>
lib_deps =
    jgromes/RadioLib


# 13. Environment for LoRa Actuator (ported from lora_actuator.ino)
[env:lora_actuator]
build_src_filter = +<main_lora_actuator.cpp> +<protocol.cpp> +<clock_config.cpp>
lib_deps =
    jgromes/RadioLib


# 14. Environment for Stop 1 Test Actuation
[env:stop1_test_actuation]
build_src_filter = +<main_stop1_test_actuation.cpp> +<clock_config.cpp>
lib_deps =
    jgromes/RadioLib


# 15. Environment for Stop 1 Advanced CAD / Rx Duty Cycle Test Actuation
[env:stop1_actuation_advanced_cad_rx_duty_cycle]
build_src_filter = +<main_stop1_actuation_Advanced-CAD_Rx_duty_cycle.cpp> +<clock_config.cpp>
lib_deps =
    jgromes/RadioLib




